### ISSUE TITLE
(s[0] == "'" and s[-1] == "'") AssertionError

### ISSUE THREAD

**Issue by MichaelDee98** [google/qkeras#56]
I am trying to use "use_stochastic_rounding" like 

```
config = {"QConv2D": {
                "kernel_quantizer":"quantized_bits()",
                "bias_quantizer":"quantized_bits(use_stochastic_rounding=True)"
				
  } 
```

but I get this error
> keras-YOLOv3-model-set/qkeras/safe_eval.py", line 42, in Num
>     (s[0] == "'" and s[-1] == "'")

**Comment by danielemoro** [comment]
Hello. Thank you for your question. 

From looking at [GetParams](https://github.com/google/qkeras/blob/master/qkeras/safe_eval.py#L48-L73), it looks like QKeras assumes that string versions of quantizers only contain lists of integers .

Therefore, the easiest way to resolve the error may be to remove the quotes around the quantizers such that instead of using the strings, you can use the imported Python classes of the quantizers instead.  

Please try the following change and let us know if it works
```
"kernel_quantizer": quantized_bits(),
"bias_quantizer": quantized_bits(use_stochastic_rounding=True) 
```
